### ISSUE TITLE
CALDAV Timezone problem 

### ISSUE THREAD

**Issue by denis-robel** [nemomobile/buteo-sync-plugin-caldav#55]
Hallo,

I have a very ugly problem:

I'm syncing my calendars with Zentyal 3.5 (SOGo/openchange) via caldav. My personal calendar is shifted by one hour and the all shard calendars of other users not.

I checked the time zone settings of the different calendars and of my phone: all are in the same zone (BERLIN).

The servers internal clock is setted to UTC and the sync with other clients like Thunderbird, Kontact or Android via caldav is working well.

Is there anybody who can help me?

with best regards

Denis

**Comment by pvuorela** [comment]
Sound like https://github.com/nemomobile/buteo-sync-plugin-caldav/issues/50

**Comment by chriadam** [comment]
I agree.  Closing this issue, as it should be fixed in version mer/4.10.2+9git10 of mer-packages-kcalcore.  If you still experience this issue after the next Sailfish OS release, please comment again on this issue.
