### ISSUE TITLE
Sync fails with multiple calenders having events with same UID

### ISSUE THREAD

**Issue by birefringence** [nemomobile/buteo-sync-plugin-caldav#59]
Synching fails with the following error if there is the same event in multiple calendars:

```
Jan 17 11:40:43 Jolla caldav-client[12301]: [C] mKCal::SqliteStorage::Private::saveIncidences:2069 - sqlitestorage.cpp: 2069 - UNIQUE constraint failed: Components.UID, Components.RecurId, Components.DateDeleted for incidence "##redacted"
```

In case you are wondering how that happens: I have both my wife's and my own calendar synched to my phone. If I invite her to an event (or vice versa) the same event will be in both calendars.

So I don't think the assumption that the UID is actually unique across multiple calendars is correct.

**Comment by chriadam** [comment]
Thanks for the report.  I guess we could create some form of compound UID which consists of the server-side UID and the notebook UID.  I will look into this.

**Comment by chriadam** [comment]
See also https://bugs.merproject.org/show_bug.cgi?id=1465

**Comment by birefringence** [comment]
I wasn't subscribed to the Mer bug, so I didn't see this is already fixed. I confirm that this is working now on Sailfish. Great :-)
